
SELECT PRODUCTO_ID, NOMBRE, PRECIO, SKU, FECHA_REGISTRO FROM TBL_PRODUCTO;

INSERT INTO TBL_PRODUCTO(PRODUCTO_ID, NOMBRE, PRECIO, SKU, FECHA_REGISTRO) VALUES (1l, 'MIMASKOT ADULTOS RAZAS PEQUEÑA 3 KG',27.57,'800493','2025-05-29');

INSERT INTO TBL_PRODUCTO(PRODUCTO_ID, NOMBRE, PRECIO, SKU, FECHA_REGISTRO) VALUES (2l, 'MIMASKOT CACHORROS RAZAS MED-GRAN 22KG',140.50,'801735','2025-05-30');


alter table tbl_producto
drop column sku;

